# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Script to list files
      run: ls -al $GITHUB_WORKSPACE
    
    - name: Hello world action step with $GITHUB_WORKSPACE
      uses: ./ # Uses an action in the root directory
      with:
        who-to-greet: $GITHUB_WORKSPACE
        steps-context: ${{ toJson(steps) }}
    
    - name: Hello world action step
      id: hello
      uses: ./ # Uses an action in the root directory
      with:
        who-to-greet: 'Mona the Octocat'
        steps-context: ${{ toJson(steps) }}
    
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, GitHub Actions!
    
    - name: Run incorrect script
      run: badcommand Hello, Error!
    
    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    
    - name: Run script if any previous step failed
      if: failure()
      run: echo "What's up, Error!"
    
    - name: Check steps context if failure
      if: failure()
      uses: ./
      with:
        who-to-greet: 'THE END'
        steps-context: ${{ toJson(steps) }}
